apiVersion: v1
kind: Service
metadata:
  name: weatherback-service
spec:
  selector:
    app: weatherback
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
  type: NodePort